const CONFIG = {
    introTitle: 'Babe à!',
    introDesc: `sáng gòi dậy đi con đĩ :3`,
    btnIntro: 'hihi',
    title: 'Chúc bấy bì có mụt bủi sáng tút lành',
    desc: 'khi nào dậy tao call cho mài nha ',
    btnYes: 'okii <33',
    btnNo: 'đéo :(( ',
    question:'ê ê có gì tao vid call cho nha :> (nói ko thì còn cái nịt:<)',
    btnReply: 'send cho tao👌',
    reply: 'có',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'mốt tao gọi m dậy nha',
    btnAccept: 'Okiiiii lun <3',
